### ISSUE TITLE
NEAT plagiarism issues

### ISSUE THREAD

**Issue by danehkar** [rwesson/NEAT#48]
https://www.nebulousresearch.org/codes/neat/plagiarism

**Comment by ashkbiz** [comment]
NEAT plagiarism issues 

All propaganda should be stopped immediately. 

Mon. Not. R. Astron. Soc. 422, 3516–3526 (2012): "NEAT incorporates elements of several previous codes, most importantly the EQUIB code, for solving the equations of statistical equilibrium in multilevel atoms."

You did not document those elements of several previous codes in your paper and code. You did not acknowledge those people who wrote EQUIB in your publication, and elements of several previous codes.

I also raised those issues and bugs of ALFA and NEAT which you did not fix.
